environment:
  matrix:
    - nodejs_version: "10.18.1"
      FLAKINESS_DASHBOARD_NAME: Appveyor Chromium (Win + node10)
  FLAKINESS_DASHBOARD_PASSWORD:
    secure: g66jP+j6C+hkXLutBV9fdxB5fRJgcQQzy93SgQzXUmcCl/RjkJwnzyHvX0xfCVnv

build: off

install:
  - ps: $env:FLAKINESS_DASHBOARD_BUILD_URL="https://ci.appveyor.com/project/aslushnikov/puppeteer/builds/$env:APPVEYOR_BUILD_ID/job/$env:APPVEYOR_JOB_ID"
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - if "%nodejs_version%" == "10.18.1" (
      npm run lint &&
      npm run coverage  &&
      npm run test-doclint &&
      npm run test-types
    )
